name = "GroebnerBasis"
uuid = "e39c9192-ea4d-5e15-9584-a488c6d614bd"
version = "0.3.0"

[deps]
BinaryProvider = "b99e7846-7c00-51b0-8f62-c81ae34c0232"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
GMP_jll = "781609d7-10c4-51f6-84f2-b8444358ff6d"
Hecke = "3e1990a7-5d81-5526-99ce-9ba3ff248f21"
LibGit2 = "76f85450-5226-5b5a-8eaa-529ad045b433"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
Nemo = "2edaba10-b0f1-5616-af89-8c11ac63239a"
Singular = "bcd08a7b-43d2-5ff7-b6d4-c458787f915c"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
gb_jll = "006bdf2e-00d8-555c-bee2-993406487cbf"

[compat]
BinaryProvider = "^0.5.8"
Hecke = "0.9.1"
Nemo = "^0.19"
Singular = "^0.4"
julia = "1.3"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
